export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div>
          <a href="/">홈페이지 가기</a>
          상단메뉴(header)
        </div>
        <div>{children}</div>
        <div>하단메뉴(footer)</div>
      </body>
    </html>
  );
}
