import { Icon, EditIcon } from "@/components/ui/icon";

import React from "react";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function eventLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <div>
        <a href="/">홈페이지 가기</a>
        상단메뉴(header)
      </div>

      <Icon as={EditIcon} size="xl" />

      <div>{children}</div>
      <div>하단메뉴(footer)</div>
    </div>
  );
}
