import Footer from "./Footer";
import Header from "./header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div className="w-full h-16" style={{ backgroundColor: "#383838" }}>
          <div className="container mx-auto">
            <Header />
          </div>
        </div>
        <div>{children}</div> {/* page내용이 children에 들어감 */}
        <div className="h-80 bg-black">
          <div className="container mx-auto">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
