import Footer from "./Footer";
import Header from "../components/Header";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        <div>
          <Header />
          <div className="lg:pl-72">{children}</div>
        </div>
        {/* page내용이 children에 들어감 */}
        <div className="lg:pl-72 h-80 bg-black">
          <div className="container mx-auto">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
